### ISSUE TITLE
1.6

### ISSUE THREAD

**Issue by DigiDuncan** [Forkk/MCRewind#6]
This is quite the big deal, as 1.6 was just launched today. There is no way, as of current, to access 1.6 using MultiMC, forcing its users to resort to the Minecraft.exe standard launcher. Will there be a fix for this?

**Comment by clanemaster1** [comment]
Get the update  
I depend on Multimc with MCRewind

**Comment by DigiDuncan** [comment]
MultiMC does not still slow for switching to 1.6. I'm in build 4.3.0 #78. If you are referring to MultiMc5, I cannot find how to compile it.

-- DigiDuncan

**Comment by jaystarkey** [comment]
http://forkk.net/update-minecraft-16-and-synctron.html
